import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConsentProvider from "@/providers/ConsentProvider";
import { Providers } from "./providers";
import { Navbar } from "@/components/shared";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout for the NextShopKit starter template
 * Sets up the basic HTML structure with providers and global styling
 * Includes parallel routing support for modals (cart, product quick view, etc.)
 */
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode; // Parallel route for modal content
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* Modal content rendered above main content */}
          {modal}
          {/* Main application content */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
